version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --no-include-email --region us-east-1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t awsome-ecr-repo .
      - docker tag awsome-ecr-repo:latest 500735694507.dkr.ecr.us-east-1.amazonaws.com/awsome-ecr-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker login -u AWS -p eyJwYXlsb2FkIjoielhNbXJnYUZmaUR0cVdoVHNQelBITUZSeWJIQVhlTnJicGcvVGtGTEpwZndmeXcyUGFJNFlENVZXQmNUbnlaOU40OUx2QWtTamFlK253anRXQ290Mk9vblZLQkNyeTZYVWZCZnJhSGhvN1Fhc3hZQlRXaUVUN0hUYmVUdUo4LzdkVjkyU1puaWVpOEliOFNjNEFJSmQ0a2lzSnBjMTE2WDZaZmc2bUdYVG5QSHlKQmRqaUtjMGtTRXNPKyt3TWkvNEJIUkdGWFBxLzhPdzArVXlOUGc1YzNOeTA5OU5mdGxiZVlsUFE0MGM5dWQyaVNpVDVxTXFpWnZ2RHl1ZUlhU0Y2OWNONm1UR1hXK2lGd0pyaEp5ZGJOOWZaVkJPRHpMaWtnalMvT2ZLWWlFWjc4S3M4TkJhZHF5MStjUmVjbDNsdHdLTG5JM3J4dnFySzZRMEVOVGthTyttWjBvb2lXdTVmajBibEtpemI2dmVjeEFwNkJjREpPanI0UmFNUC9tTm9ZdXFLbTZydVJYaWhSS24zYnZzZ1h1ckN3aTUrVWdxZWk4U2JDcThwZlhRcFB4STJKR1BxYzVsQ0VEYXl2Q3c3eUY2R0JpZlhlK21yRmM1RW9iYjlEMkRhNDV3VkN4N3AzdHI5Y3B1ZDJmaWUveFA3TjM1RURCZjlNNlFmOHpzYm0wdlNJc3poaUNSNkNuRUNjQmQ1ekFaekxQcFJKOWtPcXlWQzFya0xFUjFlNmZPZ21zM2NkMUhYNitZc0o5VXRwZ1Avd1kzWmd5TjlpYWRFZ0lMUjduNlFYVGxaR3ZRWkhScm84OVYwMXVSUGx0d2F1elhKa2M2V29YbWVydUcwS05FWGdLSUVCMmo2YjNmcElacThmb2NraTFTUTZmNWJTeVJLN2FVdWdqZ1dvRDFQcjhhM3JqWlMwellBL0F3UFZEWWEzVnB3TzVJNThEOEk2ZWdaTitvWHdpbDFJTlZ5c21PQWpJN2F1NVpVTzJkazlkaDg2TkRpOUFSWngxVlh5dXZ0dXg3eC9IUVpjcmNDMExPamxUU0luWVdaZ1VEWWZVQ3gzSWcwMllEcklCR2hsSDI3Q3Rqa3RESnFwN3NlSVBVVVpFLzQ5bm90UjUvTUlZaS9zd1ZxQTBHK2FJazFCMU9sK0xTZk5JVmVadlg2UnRMRGZId0lYdCt2bm1tYVdqUFFaNXBCckZvUE9CMTNIdjFpU0FHd3IxYjdvL1ZyajMvM2l0WGFteVZBQ0hhMFVvTzh2WjhhczdHSFYxNWhpUVdlRW1aRjNaL0FvSlpRRllXL0E0NXJmaTVQMlRCV2JYWFg3NDNFZUl6ZjNVVE9VcjZUVXpDendTNzU4VGw2YUFHeE5mbWx2RVNNdWpEZVZuWHBoNXVRbHN0ZTJPbHYxMU5QMzlTQThrNVBSOW9GbWQxeUJsIiwiZGF0YWtleSI6IkFRRUJBSGo2bGM0WElKdy83bG4wSGMwMERNZWs2R0V4SENiWTRSSXBUTUNJNThJblV3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURPZngzOERmWTJQMDNYNUk3QUlCRUlBN1cyQVZhVlFHK3NPdXl4ME9RUUV6bzR5QnR5eCtseEtMZ0RrZjNzTXlvVVNwV1QwbXFDSE1BZ2sxRzNRVW1MR2E2c3NwZ2RXLzFUdTNHbjA9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNTY5NDM2MTg3fQ== -e none https://500735694507.dkr.ecr.us-west-2.amazonaws.com
      - docker push 500735694507.dkr.ecr.us-east-1.amazonaws.com/awsome-ecr-repo:latest 
      - echo renaming _Dockerrun.aws.json file
      - mv _Dockerrun.aws.json Dockerrun.aws.json
      - echo deleting Dockerfile
      - rm Dockerfile
artifacts:
  files:
    - '**/*'
