version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --region us-east-1 | sed 's|https://||'
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t awsome-ecr-repo .
      - docker tag awsome-ecr-repo:latest 500735694507.dkr.ecr.us-east-1.amazonaws.com/awsome-ecr-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 500735694507.dkr.ecr.us-east-1.amazonaws.com/awsome-ecr-repo:latest 
      - echo renaming _Dockerrun.aws.json file
      - mv _Dockerrun.aws.json Dockerrun.aws.json
      - echo deleting Dockerfile
      - rm Dockerfile
artifacts:
  files:
    - '**/*'
